# Generated by Django 3.2.6 on 2021-08-15 07:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_books', django.db.models.manager.Manager()),
            ],
        ),
    ]
